### ISSUE TITLE
Need help understanding error in build while performing rt export

### ISSUE THREAD

**Issue by bhattacharyyasom** [retronym/java9-rt-export#1]
I am trying to do a pull request for a scala library. All the builds pass except the jdk 9 one and that errors out while doing the export of the rt.jar. I am unable to understand the issue.  The build is at https://travis-ci.org/bhattacharyyasom/scala-csv/jobs/246308372 . Please advise.

**Comment by xuwei-k** [comment]
https://github.com/tototoshi/scala-csv/pull/109

**Comment by bhattacharyyasom** [comment]
thank you for the quick response.
